repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
    -   id: gitleaks
-   repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
    -   id: actionlint
        files: '^\.github/(workflows|actions)/.*\.(yml|yaml)$'
        types_or: [yaml, text]
        always_run: true
        pass_filenames: true
