---
name: "Gitleaks Secret Scanning"

description: "Scan repositories for secrets using Gitleaks"

inputs:
  config-path:
    description: "Path to gitleaks config file"
    required: false
    default: .gitleaks.toml
  gitleaks-flags:
    description: "Additional gitleaks flags"
    required: false
    default: ''
  scan-mode:
    description: "Scan mode (latest-commit or full)"
    required: false
    default: full
  gitleaks-license-key:
    description: 'Gitleaks license key (required for org accounts)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Validate all inputs
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
        SCAN_MODE: ${{ inputs.scan-mode }}
        GITLEAKS_FLAGS: ${{ inputs.gitleaks-flags }}
        ACTION_PATH: ${{ github.action_path }}
      run: "$ACTION_PATH/validate-inputs.sh"

    - name: Run gitleaks
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
        SCAN_MODE: ${{ inputs.scan-mode }}
        SHA: ${{ github.sha }}
        WORKSPACE: ${{ github.workspace }}
        ACTION_PATH: ${{ github.action_path }}
        GITLEAKS_LICENSE_KEY: ${{ env.GITLEAKS_LICENSE_KEY }}
        GITLEAKS_FLAGS: ${{ inputs.gitleaks-flags }}
      run: |
        # Determine scan range
        if [ "$SCAN_MODE" = "latest-commit" ]; then
          LOG_OPTS="--log-opts=$SHA^..$SHA"
        else
          LOG_OPTS=""
        fi

        # Set config flag if file exists
        if [ "${CONFIG_PATH}" ] && [ -f "${CONFIG_PATH}" ]; then
          CONFIG_FLAG="--config=/repo/${CONFIG_PATH}"
          echo "Using config: ${CONFIG_PATH}"
        else
          CONFIG_FLAG="--config=/action/default-config.toml"
          echo "No .gitleaks.toml found - using Gitleaks default"
        fi

        docker run --rm \
          -v "${WORKSPACE}:/repo" \
          -v "${ACTION_PATH}:/action" \
          -e GITLEAKS_LICENSE_KEY="${GITLEAKS_LICENSE_KEY}" \
          zricethezav/gitleaks:v8.18.4@sha256:75bdb2b2f4db213cde0b8295f13a88d6b333091bbfbf3012a4e083d00d31caba \
          detect \
          --source="/repo" \
          ${LOG_OPTS} \
          ${CONFIG_FLAG} \
          --verbose \
          --redact \
          --ignore-gitleaks-allow \
          --exit-code 1 \
          ${GITLEAKS_FLAGS}
