name: 'Gitleaks Secret Scanning'
description: 'Scan repositories for secrets using Gitleaks'
author: 'Your Organization'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  config-path:
    description: 'Path to gitleaks config file'
    required: false
    default: '.github/actions/gitleaks-scanning/.gitleaks.toml'
  gitleaks-flags:
    description: 'Additional gitleaks flags'
    required: false
    default: ''
  scan-mode:
    description: 'Scan mode (latest-commit or full)'
    required: false
    default: 'latest-commit'

runs:
  using: 'composite'
  steps:
    - name: Check for config file
      id: config-check
      shell: bash
      run: |
        # if [ -f "${{ inputs.config-path }}" ]; then
        if [ -f "$CONFIG_PATH" ]; then
          echo "found=true" >> $GITHUB_OUTPUT
          echo "Using calling repository's .gitleaks.toml"
        else
          echo "found=false" >> $GITHUB_OUTPUT
          echo "No .gitleaks.toml found - using Gitleaks defaults"
        fi

    - name: Run gitleaks
      shell: bash
      env:
        SCAN_MODE: ${{ inputs.scan-mode }}
        SHA: ${{ github.sha }}
      run: |
        # Determine scan range
        # if [ "${{ inputs.scan-mode }}" = "latest-commit" ]; then
        if [ "$SCAN_MODE" = "latest-commit" ]; then
          # LOG_OPTS="--log-opts=${{ github.sha }}^..${{ github.sha }}"
          LOG_OPTS="--log-opts=$SHA^..$SHA"
        else
          LOG_OPTS=""
        fi
        # Set config flag if file exists
        if [ "${{ steps.config-check.outputs.found }}" = "true" ]; then
          CONFIG_FLAG="--config=/repo/${{ inputs.config-path }}"
        else
          CONFIG_FLAG=""
        fi
        docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          -e GITLEAKS_LICENSE_KEY="${{ env.GITLEAKS_LICENSE_KEY }}" \
          zricethezav/gitleaks:v8.18.4@sha256:75bdb2b2f4db213cde0b8295f13a88d6b333091bbfbf3012a4e083d00d31caba \
          detect \
          --source="/repo" \
          ${LOG_OPTS} \
          ${CONFIG_FLAG} \
          --verbose \
          --redact \
          --ignore-gitleaks-allow \
          --exit-code 1 \
          ${{ inputs.gitleaks-flags }}
